---
- name: System Resource Monitoring with HTML Alerts
  hosts: all
  gather_facts: yes
  become: yes

  vars:
    threshold: 80
    process_list:
      - sshd
      - nginx
    alert_file: /tmp/system_alert.html

  tasks:

    # -----------------------------------------------------------
    # CPU USAGE
    # -----------------------------------------------------------
    - name: Get CPU usage
      shell: "top -bn1 | grep 'Cpu(s)' | awk '{print 100 - $8}'"
      register: cpu_usage_raw

    - set_fact:
        cpu_usage: "{{ cpu_usage_raw.stdout | float | round(2) }}"

    # -----------------------------------------------------------
    # MEMORY USAGE
    # -----------------------------------------------------------
    - name: Get Memory usage
      shell: "free -m | awk 'NR==2{printf(\"%.2f\", $3*100/$2)}'"
      register: mem_usage_raw

    - set_fact:
        mem_usage: "{{ mem_usage_raw.stdout | float | round(2) }}"

    # -----------------------------------------------------------
    # DISK USAGE
    # -----------------------------------------------------------
    - name: Get Disk usage (root)
      shell: "df / | awk 'NR==2{print $5}' | sed 's/%//'"
      register: disk_usage_raw

    - set_fact:
        disk_usage: "{{ disk_usage_raw.stdout | float | round(2) }}"

    # -----------------------------------------------------------
    # LOAD AVERAGE
    # -----------------------------------------------------------
    - name: Get vCPU count
      set_fact:
        vcpu_count: "{{ ansible_processor_vcpus | default(2) }}"

    - name: Get load average (1 min)
      shell: "awk '{print $(NF-2)}' /proc/loadavg"
      register: load_avg_raw

    - set_fact:
        load_1min: "{{ load_avg_raw.stdout | float }}"
        load_pct_of_vcpu: "{{ ((load_avg_raw.stdout | float) * 100 / vcpu_count) | round(2) }}"

    # -----------------------------------------------------------
    # PROCESS CHECKS
    # -----------------------------------------------------------
    - name: Check required processes
      shell: "pgrep -fl {{ item }}"
      register: proc_status
      ignore_errors: yes
      loop: "{{ process_list }}"

    - name: Format process results
      set_fact:
        proc_results: |
          {% for p in proc_status.results %}
            <tr>
              <td>{{ p.item }}</td>
              <td>{{ 'Running' if p.stdout != '' else 'Not Running' }}</td>
            </tr>
          {% endfor %}

    # -----------------------------------------------------------
    # BUILD HTML ALERT
    # -----------------------------------------------------------
    - name: Build HTML alert file
      copy:
        dest: "{{ alert_file }}"
        content: |
          <html>
          <body style="font-family: Arial;">

          <h2>🚨 System Resource Alert for {{ inventory_hostname }}</h2>

          <table border="1" cellpadding="6" cellspacing="0" style="border-collapse: collapse;">

            <tr><th>Metric</th><th>Value</th></tr>

            <tr><td>CPU Usage</td><td>{{ cpu_usage }}%</td></tr>
            <tr><td>Memory Usage</td><td>{{ mem_usage }}%</td></tr>
            <tr><td>Disk Usage</td><td>{{ disk_usage }}%</td></tr>
            <tr><td>Load Average (1min)</td><td>{{ load_1min }}</td></tr>
            <tr><td>Load % of vCPU</td><td>{{ load_pct_of_vcpu }}%</td></tr>

          </table>

          <br><br>
          <h3>Process Status</h3>

          <table border="1" cellpadding="6" cellspacing="0" style="border-collapse: collapse;">
            <tr><th>Process</th><th>Status</th></tr>
            {{ proc_results }}
          </table>

          <br><br>
          <p>Alert Threshold: {{ threshold }}%</p>

          </body>
          </html>

    # -----------------------------------------------------------
    # CONDITIONAL EMAIL ALERT
    # -----------------------------------------------------------
    - name: Send alert email via mutt
      shell: >
        mutt -e "set content_type=text/html"  
        -s "🚨 ALERT: High Resource Usage on {{ inventory_hostname }}"  
        -- {{ email_to }} < {{ alert_file }}
      vars:
        email_to: "suraj.shinde@signzy.com"
      when: >
        (cpu_usage > threshold) or
        (mem_usage > threshold) or
        (disk_usage > threshold) or
        (load_pct_of_vcpu > threshold)
