---
- name: Monitor System Resources With Alert
  hosts: all
  gather_facts: yes
  become: yes

  vars:
    threshold: 80
    alert_email: "suraj.shinde@signzy.com"
    sender_email: "surajshinde59.ss@gmail.com"
    smtp_server: "smtp.example.com"
    smtp_port: 587

  tasks:

    - name: Check CPU Usage
      shell: "top -bn1 | awk '/Cpu/ {print 100 - $8}'"
      register: cpu_usage

    - name: Check Memory Usage
      shell: "free | awk '/Mem/ {printf(\"%.0f\", $3/$2 * 100)}'"
      register: mem_usage

    - name: Check Disk Usage
      shell: "df -h / | awk 'NR==2 {gsub(\"%\",\"\"); print $5}'"
      register: disk_usage

    - name: Check Load Average
      shell: "awk '{print $1}' /proc/loadavg"
      register: load_avg

    - name: Set vCPU count
      set_fact:
        vcpu_count: "{{ ansible_facts.processor_vcpus | default(1) }}"

    - name: Build alert body
      set_fact:
        alert_message: |
          Resource Alert for {{ inventory_hostname }}

          CPU Usage: {{ cpu_usage.stdout }}%
          Memory Usage: {{ mem_usage.stdout }}%
          Disk Usage: {{ disk_usage.stdout }}%
          Load Average (1min): {{ load_avg.stdout }}

          Threshold: {{ threshold }}%
      when: >
        (cpu_usage.stdout | int) > threshold or
        (mem_usage.stdout | int) > threshold or
        (disk_usage.stdout | int) > threshold or
        ((load_avg.stdout | float * 100 / vcpu_count) > threshold)

    - name: Send alert email
      mail:
        host: "{{ smtp_server }}"
        port: "{{ smtp_port }}"
        to: "{{ alert_email }}"
        from: "{{ sender_email }}"
        subject: "ALERT: Resource Threshold Exceeded on {{ inventory_hostname }}"
        body: "{{ alert_message }}"
      when: alert_message is defined

    - name: Print Metrics
      debug:
        msg:
          - "CPU: {{ cpu_usage.stdout }}%"
          - "MEM: {{ mem_usage.stdout }}%"
          - "DISK: {{ disk_usage.stdout }}%"
          - "LOAD: {{ load_avg.stdout }}"
          - "vCPU count: {{ vcpu_count }}"
